name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: vscode-extension/package-lock.json
      
      - name: Make CI script executable
        run: chmod +x scripts/ci.sh

      - name: Run CI checks
        run: ./scripts/ci.sh
      
      - name: Create VSIX package
        run: |
          cd vscode-extension
          npm install -g @vscode/vsce
          vsce package
          echo "VSIX_PATH=$(find . -name '*.vsix')" >> $GITHUB_ENV
          echo "VSIX_NAME=$(basename $(find . -name '*.vsix'))" >> $GITHUB_ENV
      
      - name: Upload VSIX to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vscode-extension/${{ env.VSIX_NAME }}
          asset_name: ${{ env.VSIX_NAME }}
          asset_content_type: application/octet-stream
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: vscode-extension/out/ 